name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      pages: write      
      actions: read     

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: GitHub Pages aktivieren
        uses: actions/configure-pages@v3

      - name: Jekyll Setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'

      - name: Jekyll bauen
        run: |
          gem install bundler jekyll
          jekyll build --destination ./_site

      - name: Deployment auf gh-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Veröffentlichen
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
