name: Build and Deploy Markdown to GitHub Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: write 
  pages: write    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Pandoc installieren
        run: sudo apt-get install -y pandoc

      - name: Markdown in HTML umwandeln
        run: |
          mkdir output
          # Konvertiere README.md und benenne es als index.html
          pandoc -s README.md -o output/index.html
          # Konvertiere alle anderen .md-Dateien in HTML
          for file in *.md; do
            [ -f "$file" ] || continue
            filename=$(basename "$file" .md)
            pandoc -s "$file" -o "output/$filename.html"
          done

      - name: GitHub Pages veröffentlichen
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  
          folder: output    
